name: Bug Report
description: Something's not working right
title: "[Bug]: "
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug!
        
        Before submitting, please search existing issues to avoid duplicates.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us what went wrong
      placeholder: I tried to run psx check and it crashed...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      description: What should have happened instead?
      placeholder: It should have checked my project and showed results
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce
      description: Steps to reproduce the issue
      placeholder: |
        1. Run `psx check` in my project
        2. See error message
        3. ...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: PSX Version
      description: Run `psx version` to get this
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error logs or output
      description: Paste any error messages or output here
      render: shell
      placeholder: |
        $ psx check
        Error: something went wrong...

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Anything else we should know?
      placeholder: This only happens when I have a .gitignore file...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and didn't find a duplicate
          required: true
        - label: I'm using the latest version of PSX
          required: false