name: Feature Request
description: Suggest something new
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Got an idea? Let's hear it!

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Is there something that's currently difficult or impossible?
      placeholder: I want to check X but psx doesn't support it...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What would you like to see?
      description: Describe your ideal solution
      placeholder: It would be cool if psx could...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
      description: Are there workarounds or other tools that do this?
      placeholder: Currently I'm using X but it's not great because...

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - Nice to have
        - Would be helpful
        - Pretty important
        - Blocking my work
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Anything else? Screenshots, examples, etc.

  - type: checkboxes
    id: willing
    attributes:
      label: Contribution
      options:
        - label: I'd be willing to implement this myself with guidance
          required: false