package config

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"testing"
)

// docsHeader marks a generated file so hand edits are noticed.
const docsHeader = "<!-- Generated by `make docs`. Do not edit by hand. -->"

// ruleReferencePath is the generated catalogue.
const ruleReferencePath = "../../docs/RULES.md"

// TestGenerateRuleReference writes docs/RULES.md from rules.yml.
//
// The catalogue has to come from the same source the engine reads, or the
// documentation drifts the moment a rule is added.
func TestGenerateRuleReference(t *testing.T) {
	body := renderRuleReference()

	if err := os.WriteFile(ruleReferencePath, []byte(body), 0o644); err != nil {
		t.Fatalf("write docs/RULES.md: %v", err)
	}
	t.Logf("wrote docs/RULES.md (%d rules)", len(GetRulesMetadata().Rules))
}

// TestRuleReferenceIsUpToDate fails when the committed catalogue no longer
// matches rules.yml.
//
// Skipped under -short, so a quick unit-test pass skips the file write while
// `make check` and CI enforce freshness.
func TestRuleReferenceIsUpToDate(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping generated-file freshness check in short mode")
	}

	committed, err := os.ReadFile(ruleReferencePath)
	if err != nil {
		t.Fatalf("read docs/RULES.md (run `make docs`): %v", err)
	}

	if want := renderRuleReference(); string(committed) != want {
		t.Errorf("docs/RULES.md is out of date; run `make docs`")
	}
}

// renderRuleReference builds the markdown catalogue.
func renderRuleReference() string {
	all := GetRulesMetadata().Rules

	byCategory := map[string][]string{}
	fixable, safe := 0, 0
	for id, m := range all {
		byCategory[m.Category] = append(byCategory[m.Category], id)
		if m.Fixable() {
			fixable++
			if m.Fix.Safe {
				safe++
			}
		}
	}

	categories := make([]string, 0, len(byCategory))
	for c := range byCategory {
		categories = append(categories, c)
	}
	sort.Strings(categories)

	var b strings.Builder
	b.WriteString(docsHeader + "\n\n")
	b.WriteString("# Rule reference\n\n")
	fmt.Fprintf(&b, "%d rules in %d categories. %d can be created automatically", len(all), len(categories), fixable)
	if safe > 0 && safe < fixable {
		fmt.Fprintf(&b, ", of which %d are safe for `psx watch --fix`", safe)
	} else if safe == fixable && safe > 0 {
		b.WriteString(", all of them safe for `psx watch --fix`")
	}
	b.WriteString(".\n\n")
	b.WriteString("Severity is the default; override it per project in `psx.yml`:\n\n")
	b.WriteString("```yaml\nrules:\n  readme: error\n  license: false   # disabled\n```\n\n")
	b.WriteString("Run `psx explain <rule>` for one rule in full, or `psx rules` for this list.\n")

	for _, cat := range categories {
		ids := byCategory[cat]
		sort.Strings(ids)

		fmt.Fprintf(&b, "\n## %s (%d)\n\n", categoryTitle(cat), len(ids))
		b.WriteString("| Rule | Severity | Fix | Creates | Description |\n")
		b.WriteString("| --- | --- | --- | --- | --- |\n")

		for _, id := range ids {
			m := all[id]
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s |\n",
				id, m.DefaultSeverity, fixLabel(m), createdPaths(m), m.Description)
		}
	}

	return b.String()
}

func fixLabel(m RuleMetadata) string {
	switch {
	case !m.Fixable():
		return "manual"
	case m.Fix.Safe:
		return "auto (safe)"
	default:
		return "auto"
	}
}

// createdPaths lists the literal paths a fix writes, inline and compact.
func createdPaths(m RuleMetadata) string {
	if !m.Fixable() {
		return "—"
	}
	var out []string
	if m.Fix.Path != "" {
		out = append(out, "`"+m.Fix.Path+"`")
	}
	paths := make([]string, 0, len(m.Fix.Files))
	for p := range m.Fix.Files {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	for _, p := range paths {
		out = append(out, "`"+p+"`")
	}
	return strings.Join(out, "<br>")
}

// categoryLabels gives acronyms their proper casing.
var categoryLabels = map[string]string{
	"cicd": "CI/CD",
}

func categoryTitle(cat string) string {
	if label, ok := categoryLabels[cat]; ok {
		return label
	}
	if cat == "" {
		return cat
	}
	return strings.ToUpper(cat[:1]) + cat[1:]
}
